[project]
name = "prestamos-bimestrales"
revision = "1.0"

[profiles.development]
DB_NAME = { description = "DB_NAME secret", required = true }
DB_PASSWORD = { description = "DB_PASSWORD secret", required = true }
DB_USER = { description = "DB_USER secret", required = true }
JWT_EXPIRES_IN = { description = "JWT_EXPIRES_IN secret", required = true }
JWT_SECRET = { description = "JWT_SECRET secret", required = true }
